-- 1. Create the sermons table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.sermons (
    id bigint generated by default as identity primary key,
    title text not null,
    preacher text,
    date date default now(),
    thumbnail text,
    url text,
    type text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create the prayer_requests table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.prayer_requests (
    id bigint generated by default as identity primary key,
    name text,
    phone text,
    request text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable RLS for both tables
ALTER TABLE public.sermons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prayer_requests ENABLE ROW LEVEL SECURITY;

-- 4. Policies for sermons
-- Allow everyone to read sermons (SELECT)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read access for sermons') THEN
        CREATE POLICY "Allow public read access for sermons" ON public.sermons FOR SELECT TO anon, authenticated USING (true);
    END IF;
END $$;

-- Allow authenticated users (admins) to manage sermons (ALL)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow admin management for sermons') THEN
        CREATE POLICY "Allow admin management for sermons" ON public.sermons FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;
END $$;

-- 5. Policies for prayer_requests
-- Allow anyone to submit a prayer request (INSERT)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert for prayer_requests') THEN
        CREATE POLICY "Allow public insert for prayer_requests" ON public.prayer_requests FOR INSERT TO anon, authenticated WITH CHECK (true);
    END IF;
END $$;

-- Allow authenticated users (admins) to see all requests (SELECT)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow admin read for prayer_requests') THEN
        CREATE POLICY "Allow admin read for prayer_requests" ON public.prayer_requests FOR SELECT TO authenticated USING (true);
    END IF;
END $$;

-- Allow authenticated users (admins) to manage requests (ALL)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow admin management for prayer_requests') THEN
        CREATE POLICY "Allow admin management for prayer_requests" ON public.prayer_requests FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;
END $$;
