-- Create the live_stream table
create table if not exists public.live_stream (
  id bigint generated by default as identity primary key,
  is_live boolean default false,
  live_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert the default configuration row (id=1)
insert into public.live_stream (id, is_live, live_url)
values (1, false, '')
on conflict (id) do nothing;

-- Enable Row Level Security (RLS)
alter table public.live_stream enable row level security;

-- Allow everyone (anon and logged in) to read the status
create policy "Enable read access for all users"
on public.live_stream for select
to anon, authenticated
using (true);

-- Allow only logged in users (admins) to update the status
create policy "Enable update for authenticated users only"
on public.live_stream for update
to authenticated
using (true)
with check (true);

-- Allow only logged in users (admins) to insert (if needed)
create policy "Enable insert for authenticated users only"
on public.live_stream for insert
to authenticated
with check (true);
